package com.example.droponairdemo.service;

import org.springframework.stereotype.Service;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * In-memory public key directory for the demo.
 *
 * In a production implementation this should be persisted in a database
 * and support multiple devices per user (see multi-device section of the docs).
 *
 * Users publish their X25519 public key (base64) via PUT /api/droponair/keys/me
 * and fetch peer keys via GET /api/droponair/keys/{userId}.
 *
 * DropOnAir never stores or validates user keys, that responsibility belongs
 * to the customer backend (this service).
 */
@Service
public class KeyDirectoryService {

    /**
     * userId → list of { deviceId, publicKey (base64) }
     * Single-device demo stores only the latest key per user.
     */
    private final ConcurrentHashMap<String, DeviceKey> keys = new ConcurrentHashMap<>();

    public record DeviceKey(String deviceId, String publicKey) {}

    /**
     * Stores or updates the public key for a user.
     *
     * @param userId    the user's identifier
     * @param deviceId  the device identifier (from X-Device-Id header or generated by SDK)
     * @param publicKey the X25519 public key, base64-encoded
     */
    public void putKey(String userId, String deviceId, String publicKey) {
        keys.put(userId, new DeviceKey(deviceId, publicKey));
    }

    /**
     * Returns the public key record for a user, or null if not found.
     */
    public DeviceKey getKey(String userId) {
        return keys.get(userId);
    }

    /**
     * Returns all registered keys (for administrative purposes).
     */
    public Map<String, DeviceKey> allKeys() {
        return Collections.unmodifiableMap(keys);
    }

    /**
     * Returns multiple device keys for a user.
     * In this demo each user has at most one device, so this always returns a list of 0 or 1.
     */
    public List<DeviceKey> getDeviceKeys(String userId) {
        DeviceKey key = keys.get(userId);
        return key != null ? List.of(key) : List.of();
    }
}
